### ISSUE TITLE
Parallelize

### ISSUE THREAD

**Issue by carols10cents** [carols10cents/zopfli#17]
[Since zopfli splits the file into chunks before trying to compress them](https://github.com/carols10cents/zopfli/blob/master/src/deflate.rs#L884-L890), that might be a good spot to fork a bunch of threads.

There's also [a fork of zopfli that has implemented multi-threading in C](https://github.com/MrKrzYch00/zopfli), take a look to see how they're parallelizing the work.

**Comment by mmstick** [comment]
I've gained a lot of experience in parallelizing things of late for our projects at System76. I can take a look at this if no one else is interested. Perhaps over the weekend.
