### ISSUE TITLE
Profile with oxipng images

### ISSUE THREAD

**Issue by carols10cents** [carols10cents/zopfli#37]
In #36, @shssoichiro reported this lib taking 25 s in release mode with images in https://github.com/shssoichiro/oxipng/tree/master/tests/files :( :( :(

**Comment by shssoichiro** [comment]
I've done some brief benchmarking from directly in zopfli as well and here is what I found:

10 kb text file: 100ms
35 kb text file: 2.5s
Image data (600kb uncompressed): 25s

So it seems the time issue is not just with PNG images, and it grows non-linearly with filesize. :(

I did some basic profiling with the 35kb text file (which is [here](https://github.com/madler/zlib/blob/master/doc/rfc1951.txt)) and the hottest functions appear to be katajainen.rs:boundary_pm (which recursively calls itself) and lz77.rs:find_longest_match_loop.

**Comment by carols10cents** [comment]
Awesome, thanks for the info!!!

**Comment by dfrankland** [comment]
[I've created a crate](https://github.com/dfrankland/zopfli-rs) which directly binds to [`google/zopfli`](https://github.com/google/zopfli) and then ran benchmarks against it and this crate. Both crates follow the same non-linear pattern of results in regards to file size and time to compress.

Check out the results, or run the benchmarks yourself here:
https://github.com/dfrankland/zopfli-rs#benchmarks
