### ISSUE TITLE
zopfli::compress requires ownership of out parameter

### ISSUE THREAD

**Issue by AlexTMjugador** [carols10cents/zopfli#42]
Currently, the signature of the `zopfli::compress` method requires an owned struct that implements the Write trait to function, `out`. This means that `out` is dropped when the `zopfli::compress` method finishes execution, which is adequate when `out` is a file that shouldn't be touched after. However, as this means that the calling function no longer has the ownership of `out` after calling `zopfli::compress`, it can no longer use it, which is inadequate for use cases where the calling code needs to keep the ownership of the data sink.

For instance, consider this sample and incomplete Rust code that doesn't compile, which is meant to compress in-memory data and keep its compressed version in memory:

```rust
fn compress(data: &Vec<u8>) -> Vec<u8> {
	let vec_buffer = Vec::with_capacity(data.len());
	zopfli::compress(
		&zopfli::Options {
			verbose: false, verbose_more: false,
			numiterations: 8, blocksplittingmax: 15
		},
		&zopfli::Format::Deflate,
		data, vec_buffer
	);
	vec_buffer
}
```

As `vec_buffer` ownership is transferred in the call to `zopfli::compress`, the caller function can no longer return it.

I've thought about writing the result of `zopfli::compress` to a temporary file and reading it to memory again later, but that's ugly. Also, using a Cursor or Rc doesn't really help. If `zopfli::compress` accepted a reference to `out`, or its result returned `out`, I think this issue could be solved, but I didn't dig enough in the source code of this repository to know how feasible that is.

**Comment by AlexTMjugador** [comment]
Nevermind, issue #36 shows a similar function that works for this use case. Sorry for not looking at that issue before!

**Comment by shepmaster** [comment]
To be clear, the `compress` function accepts any type implementing `Write`. A mutable reference to a type that implements `Write` *also* implements `Write`, and you can use [`Write::by_ref`](https://doc.rust-lang.org/std/io/trait.Write.html#method.by_ref) to get one. 

This is a common Rust pattern. See [this SO question](https://stackoverflow.com/questions/31374051/why-does-iteratortake-while-take-ownership-of-the-iterator) for the same thing applied to iterators.
